services:
  otk:
    image: alejandrodlrocha/otk:latest
    container_name: otk
    restart: unless-stopped
    ports:
      - "7654:7654"
    volumes:
      - otk-data:/data
      - endlessh-log:/endlessh-log:ro

  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    restart: unless-stopped
    ports:
      - "22:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MSDELAY=10000
      - MAXLINES=32
      - MAXCLIENTS=4096
      - LOGFILE=true
    volumes:
      - endlessh-log:/config/log

volumes:
  otk-data:
  endlessh-log:
